# Generated by Django 5.1.1 on 2024-09-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={},
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='default',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='apartment_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='zip',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='46ce4c', max_length=6),
        ),
    ]
