# Generated by Django 5.1.1 on 2024-09-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_billingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5099c7', max_length=6),
        ),
    ]
