# Generated by Django 4.2 on 2024-09-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_payment_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='momo_transaction_id',
            new_name='paystack_charge_id',
        ),
    ]
