from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    MyOrderedSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    filter_products,
    payment_verification,
    signup,
    verify_email,
    resend_otp,
    signin,
    logout_view,
    my_orders,
    delete_order,
    thank_you_view,
    user_profile
)
from django.views.generic import TemplateView
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path("register/", signup, name="register"),
    path('verifyemail/<str:username>/', verify_email, name='verifyemail'),
    # path("verify-email/<slug:username>", verify_email, name="verify-email"),
    path("resendotp", resend_otp, name="resendotp"),
    path("signin/", signin, name="signin"),
    path('logout/', logout_view, name='logout'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('thank-you/', thank_you_view, name='thank_you'),
    path('profile/', user_profile, name='user-profile'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('delete-order/<int:order_id>/', delete_order, name='delete-order'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('my-ordered-summary/', MyOrderedSummaryView.as_view(), name='my-order-summary'),
    path('my-orders/', my_orders, name='my-orders'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment-verification/', payment_verification, name='payment-verification'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('filter/', filter_products, name='filter-products'),
    path('add-to-cart/<slug:slug>/', add_to_cart, name='add-to-cart'),
    path('remove-single-item-from-cart/<slug:slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('remove-from-cart/<slug:slug>/', remove_from_cart, name='remove-from-cart'),

]
